// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.AlgoStore.Service.History.Client.AutorestClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for HistoryAPI.
    /// </summary>
    public static partial class HistoryAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startFrom'>
            /// </param>
            /// <param name='endOn'>
            /// </param>
            /// <param name='indicatorName'>
            /// </param>
            public static object GetCandles(this IHistoryAPI operations, System.DateTime startFrom, System.DateTime endOn, string indicatorName)
            {
                return operations.GetCandlesAsync(startFrom, endOn, indicatorName).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startFrom'>
            /// </param>
            /// <param name='endOn'>
            /// </param>
            /// <param name='indicatorName'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetCandlesAsync(this IHistoryAPI operations, System.DateTime startFrom, System.DateTime endOn, string indicatorName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCandlesWithHttpMessagesAsync(startFrom, endOn, indicatorName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IsAliveResponse IsAlive(this IHistoryAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IsAliveResponse> IsAliveAsync(this IHistoryAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
